### ISSUE TITLE
Channel gets pinged whether option is toggled or not

### ISSUE THREAD

**Issue by BrziHR** [sportalliance/graylog-plugin-slack-notification#1]
Using the latest release of the plugin on graylog/graylog:3.1.2-1 Docker image we always get an "@channel" ping. I've noticed that the checkbox to toggle sending "@channel" wide pings can be checked but it doesn't get updated. Some other info about the environment if it can help:

MongoDB server version: 3.6.14
Elasticsearch version: 5.6.13

**Comment by sboeingSPA** [comment]
Hej @BrziHR 
thank you for the info!

I will take a look on it the next days

**Comment by sboeingSPA** [comment]
Hej @BrziHR,
please have a look on the new release.
I think the issue was the not visualized default value for the `notifyChannel` checkbox which was `true`.

I tested it on my local environment and for me it looks like it is working now.

**Comment by BrziHR** [comment]
I just tested it out with the new release. Doesn't work. To be sure I wiped all of the data and started the whole Graylog set up anew and it sadly still doesn't work. Nothing in the logs as well :/

What Graylog version are you using in your local environment? Is it 3.1.2-1 as well?

**Comment by BrziHR** [comment]
Also to be more exact `Link Names (optional)` also doesn't want to stay toggled. It seems that adding the false in the commit hasn't solved the first issue as it is still sending an `@channel` ping.

**Comment by sboeingSPA** [comment]
I'm using the 3.1 docker container but that should not really make a difference

I fixed now the issue that the status of the checkboxes is not correctly visualized when editing a notification but after the last fix i could not reproduce the issue that the `@channel` is always used.

When testing please make sure that the website is not cached by your browser. I'm using Chrome and during development i sometimes had problems that after restarting Graylog the browser still showed the old notification-page. So please make sure to have the new website for example by clearing the website cache and do a hard reload.

**Comment by BrziHR** [comment]
Sorry for the late response. Seems to work as intended now! Thank you so much for the fast response time.
