### ISSUE TITLE
Description not included in notification

### ISSUE THREAD

**Issue by BrziHR** [sportalliance/graylog-plugin-slack-notification#3]
Hi,

The event definition description does not get sent when using the "Test Notification" button. I haven't yet tested if it gets sent when an actual log message is sent. Using latest Graylog image (3.1.3-1).

Also would it be possible to completely drop the description bar from the notification if we are not using it?

Thanks in advance.

**Comment by sboeingSPA** [comment]
Hi @BrziHR,

thank you for raising the issue.
I will take a look into your problem next weekend

**Comment by sboeingSPA** [comment]
Hej @BrziHR ,

sadly i could not reproduce your problems using Graylog 3.1.3-1 and version 1.0.4 of this plugin.

The following message was created using the "Execute Test Notification" button. As you see it contains a "Event Definition Test Description":
<img width="576" alt="Screen Shot 2019-11-16 at 11 56 00" src="https://user-images.githubusercontent.com/50195969/68992340-48410e00-086a-11ea-8a2b-591596a0177c.png">

Next i sent a real notification without any event definition description:
<img width="546" alt="Screen Shot 2019-11-16 at 12 05 30" src="https://user-images.githubusercontent.com/50195969/68992368-bb4a8480-086a-11ea-94dd-ef6126f041c7.png">

And the last test was a real notification containing an event definition description:
<img width="541" alt="Screen Shot 2019-11-16 at 12 06 09" src="https://user-images.githubusercontent.com/50195969/68992374-cef5eb00-086a-11ea-90b4-05be487aa928.png">


So for me it looks like everything is working.
The only problem i could imagine is that you are maybe confused that the description of the **Event Definition** and not of the **Notification Definition** is used in the slack message?

**Comment by Darcloud1707** [comment]
@sboeingSPA hi, can you tell me, what field do you use for "Last messages for this alert"?

**Comment by pbrzica** [comment]
Works after I used a clean container. Sorry for any trouble.
